/**
 * 关卡包（自动生成，请勿手工编辑）。
 *
 * 生成命令：npm run gen:levels
 * 来源：自绘房间模板 + 固定种子反向拉动生成（天然可解）。
 * 校验：test/levels.test.ts 用独立 A* 求解器复核每一关，并按 source 复算生成结果比对。
 */
import type { LevelDef } from './level.js'

export const LEVEL_DEFS: LevelDef[] = [
  {
    id: "L01",
    difficulty: "starter",
    grid: [
      "#######",
      "#     #",
      "# $.  #",
      "#  #  #",
      "#  .$@#",
      "#     #",
      "#######",
    ],
    source: { kind: 'generated', roomId: "nook", seed: 1001, unpushSteps: 2 },
  },
  {
    id: "L02",
    difficulty: "starter",
    grid: [
      "#######",
      "#     #",
      "#  *  #",
      "#  #  #",
      "#@$.  #",
      "#     #",
      "#######",
    ],
    source: { kind: 'generated', roomId: "nook", seed: 1011, unpushSteps: 3 },
  },
  {
    id: "L03",
    difficulty: "starter",
    grid: [
      "########",
      "#      #",
      "# *  *@#",
      "#      #",
      "# #  # #",
      "# .$   #",
      "#      #",
      "########",
    ],
    source: { kind: 'generated', roomId: "twin", seed: 1021, unpushSteps: 3 },
  },
  {
    id: "L04",
    difficulty: "starter",
    grid: [
      "########",
      "#      #",
      "# .$@* #",
      "#  $   #",
      "# #  # #",
      "# .    #",
      "#      #",
      "########",
    ],
    source: { kind: 'generated', roomId: "twin", seed: 1031, unpushSteps: 4 },
  },
  {
    id: "L05",
    difficulty: "starter",
    grid: [
      "##########",
      "#        #",
      "#  .##.$ #",
      "#  $##$  #",
      "# $+##.  #",
      "#        #",
      "##########",
    ],
    source: { kind: 'generated', roomId: "island", seed: 1041, unpushSteps: 4 },
  },
  {
    id: "L06",
    difficulty: "starter",
    grid: [
      "#########",
      "#       #",
      "# $+$.  #",
      "#  ###  #",
      "#   *   #",
      "#  ###  #",
      "#   *   #",
      "#       #",
      "#########",
    ],
    source: { kind: 'generated', roomId: "pillars", seed: 1051, unpushSteps: 4 },
  },
  {
    id: "L07",
    difficulty: "skilled",
    grid: [
      "########",
      "#      #",
      "# .$@* #",
      "#      #",
      "# #  # #",
      "# .$   #",
      "#      #",
      "########",
    ],
    source: { kind: 'generated', roomId: "twin", seed: 2001, unpushSteps: 6 },
  },
  {
    id: "L08",
    difficulty: "skilled",
    grid: [
      "##########",
      "#        #",
      "#  *##.$@#",
      "# $ ##   #",
      "#  .##.$ #",
      "#        #",
      "##########",
    ],
    source: { kind: 'generated', roomId: "island", seed: 2011, unpushSteps: 6 },
  },
  {
    id: "L09",
    difficulty: "skilled",
    grid: [
      "#########",
      "#       #",
      "#  * .  #",
      "#  ###$ #",
      "#   .$@ #",
      "#  ###  #",
      "#  $.   #",
      "#       #",
      "#########",
    ],
    source: { kind: 'generated', roomId: "pillars", seed: 2021, unpushSteps: 6 },
  },
  {
    id: "L10",
    difficulty: "skilled",
    grid: [
      "###########",
      "#         #",
      "# $.   .  #",
      "#     @$  #",
      "#   ###   #",
      "#   *#*   #",
      "#  $###   #",
      "#  .  $.  #",
      "###########",
    ],
    source: { kind: 'generated', roomId: "pockets", seed: 2031, unpushSteps: 6 },
  },
  {
    id: "L11",
    difficulty: "skilled",
    grid: [
      "###########",
      "#         #",
      "# @*   *  #",
      "#         #",
      "#   ###   #",
      "#         #",
      "# $ ### $ #",
      "#  .   .  #",
      "###########",
    ],
    source: { kind: 'generated', roomId: "hall", seed: 2041, unpushSteps: 6 },
  },
  {
    id: "L12",
    difficulty: "challenging",
    grid: [
      "##########",
      "# @      #",
      "# $.##.$ #",
      "#   ## $ #",
      "#  *##.  #",
      "#        #",
      "##########",
    ],
    source: { kind: 'generated', roomId: "island", seed: 3001, unpushSteps: 8 },
  },
  {
    id: "L13",
    difficulty: "challenging",
    grid: [
      "#########",
      "#       #",
      "#  * .  #",
      "#  ###  #",
      "#@$ . $ #",
      "#  ###  #",
      "#  $.   #",
      "#       #",
      "#########",
    ],
    source: { kind: 'generated', roomId: "pillars", seed: 3011, unpushSteps: 8 },
  },
  {
    id: "L14",
    difficulty: "challenging",
    grid: [
      "###########",
      "#         #",
      "#@$.   *  #",
      "#         #",
      "#   ### $ #",
      "# $ .#.   #",
      "#   ###   #",
      "#  *   *  #",
      "###########",
    ],
    source: { kind: 'generated', roomId: "pockets", seed: 3021, unpushSteps: 8 },
  },
  {
    id: "L15",
    difficulty: "challenging",
    grid: [
      "###########",
      "#         #",
      "#  *   .  #",
      "#         #",
      "#   ###$  #",
      "# @       #",
      "# $ ### $ #",
      "#  .   .  #",
      "###########",
    ],
    source: { kind: 'generated', roomId: "hall", seed: 3031, unpushSteps: 8 },
  },
  {
    id: "L16",
    difficulty: "challenging",
    grid: [
      "###########",
      "#         #",
      "#  .   .  #",
      "#    $    #",
      "#   ###$  #",
      "#         #",
      "#   ### $ #",
      "#  .$@ .  #",
      "###########",
    ],
    source: { kind: 'generated', roomId: "hall", seed: 3041, unpushSteps: 10 },
  },
]

/** 生成时得到的见证解法（动作方向序列）；仅用于校验，不作为游戏内提示功能 */
export const LEVEL_WITNESSES: Record<string, string[]> = {
  "L01": ["left","up","up","left","up","left","left","down","right","up","right","right"],
  "L02": ["right","right","down","right","right","up","left","right","down"],
  "L03": ["left","up","left","left","down","right","down","down","down","left","right","right","down"],
  "L04": ["left","down","down","right","down","left","right","down"],
  "L05": ["up","left","left","down","right","up","up","up","right","right","right","right","down","down","right","right","up","left","up","left","left","left","left","left","down","down"],
  "L06": ["right","up","right","right","down","down","down","left","left","right","right","up","up","up","left","left","left","left","left","down","right","down","down","right","left","up","up","up","right","right","right","right","down"],
  "L07": ["left","right","up","right","right","down","left","down","left","down","down","left","up","up","up","up","right","down","left","down","down","right","up","left","up","right","up"],
  "L08": ["left","up","left","left","left","left","down","left","left","down","down","right","right","up","down","left","left","up","up","right","down","left","down","right","down","right","right","right","right","right","right","up","left","down","left","left","left","left","left","left","up"],
  "L09": ["up","down","down","down","left","left","down","left","left","up","right","down","right","right","right","up","up","up","left","right","right","up","up","left","up","left","left","down","right","up","right","right","down","left","down","down"],
  "L10": ["right","up","right","right","down","left","up","left","left","left","left","left","down","left","down","down","down","down","right","right","right","right","left","left","left","left","up","up","right","down","left","left","up","up","up","up","right","up","right","right","right","right","right","right","down","down","down","left","up","left","up","up"],
  "L11": ["right","left","down","down","down","down","left","down","right","up","right","up","right","right","right","right","right","right","down","left","up","left","up","up","left","left","up","left","right","right","down","right","down","down","down","up","left","left","left","left","left","up","up","up","up"],
  "L12": ["down","down","right","up","up","right","right","right","right","right","down","down","left","down","left","down","left","left","left","up","down","left","left","up","up","right","up","right","up","right","right","right","down","down","right","right","up","left","down","down","down","left","left","left","left","up","up","left","left","down","right","down","right","right","right","right","right","right","up"],
  "L13": ["right","down","down","right","down","right","right","right","right","up","up","up","up","left","down","right","down","down","left","up","up","up","right","up","left","up","left","left","left","left","down","down","down","right","left","down","down","right","down","right","right","right"],
  "L14": ["right","down","right","right","right","right","right","right","right","down","left","up","left","down","up","left","left","left","left","left","left","down","down","right","up","up","up","up","right","down","right","right","right","down","right","right","down","down","left","up","up","left","left","left","up","left","left","down","down","right","up","left","down","down","right","left","up","up"],
  "L15": ["down","right","up","right","right","right","right","up","right","down","down","left","up","up","up","right","right","down","down","down","down","left","up","up","up","up","up","left","down","left","left","left","left","left","left","down","down","down","down","right","up","right","up","up","up","right","right","up","right","left","left","down","left","left","left","down","down","down"],
  "L16": ["left","right","right","right","up","up","up","right","up","up","left","left","down","left","left","right","right","right","down","right","up","right","up","left","right","down","down","down","down","left","up","left","down","up","left","left","left","left","up","up","left"],
}
